- name: PLAY1
  host: local
  connection: local
  tasks:
  - name: hello from play1 and task1
    ansible.builtin.debug:
      msg: "Hello from play-1 and task-1"
  
  - name: hello from play1 and task2
    ansible.builtin.debug:
      msg: "Hello from play-1 and task-2"

- name: PLAY2
  host: local
  connection: local
  tasks:
  - name: hello from play2 and task1
    ansible.builtin.debug:
      msg: "Hello from play-2 and task-1"
  
  - name: hello from play2 and task2
    ansible.builtin.debug:
      msg: "Hello from play-2 and task-2"

  


    