- name: PLAY1
  host: local
  connection: local
  tasks:
  - name: hello from play1 and task1
    ansible.builtin.debug:
      msg: "Hello from play-1 and task-1"
  
  - name: hello from play1 and task2
    ansible.builtin.debug:
      msg: "Hello from play-1 and task-2"



  


    