- name: loops
  hosts: local
  connection: local
  tasks:
  - name: priniting the items from loops
    ansible.builtin.debug:
      msg: "Hello, {{ item }}"  #item here is reserved keyword
    loop:
    - Suresh
    - Ramesh
    - Yuva
    - Chotu
