- name: install packages
  hosts: frontend
  become: yes
  tasks:
  - name: installting packages
    ansible.builtin.dnf:
      msg: "Packages are, {{ item }}"
      state: installed
    loop:
    - mysql
    - nginx
    - python3
    