- name: install packages
  hosts: frontend
  become: yes
  tasks:
  - name: installting packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: installed
    loop:
    - mysql
    - nginx
    - python3
    