- name: install packages and uninstall packages
  hosts: frontend
  become: yes
  tasks:
    - name: install packages
      ansible.builtin.package:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      loop:
      - { name: 'mysql', state: 'present' }
      - { name: 'nginx', state: 'absent' }
      - { name: 'python3', state: 'present' }


